<?php
echo "\n";
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "  <head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "    <link href=https://stitches.hyperyolo.com/public/stitches.css rel=\"stylesheet\">\n";
echo "    <link href=https://fonts.googleapis.com/css?family=Muli:300,400,600,700,800,900 rel=\"stylesheet\">\n";
echo "    <link rel=\"stylesheet\" href=https://use.fontawesome.com/releases/v5.6.3/css/all.css integrity=sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/ crossorigin=\"anonymous\">\n";
echo "    <title>Stitches</title>\n";
echo "  </head>\n";
echo "  <body><nav class=\"font-sans bg-white text-center flex justify-between my-4 mx-auto container overflow-hidden\">\n";
echo "  <a href=\"/\" class=\"block text-left\">\n";
echo "    <img src=\"https://stitches-cdn.hyperyolo.com/logo.png\" class=\"h-10 sm:h-10 rounded-full\" alt=\"logo\">\n";
echo "  </a>\n";
echo "  <ul class=\"text-sm text-grey-dark list-reset flex items-center\">\n";
echo "    <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey-darkest hover:text-grey-dark no-underline\">Products</a></li>\n";
echo "    <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey-darkest hover:text-grey-dark no-underline\">Pricing</a></li>\n";
echo "    <li class=\"pr-2\"><a href=\"#\" class=\"inline-block py-2 px-3 text-grey-darkest hover:text-grey-dark no-underline\">FAQs</a></li>\n";
echo "    <li class=\"pl-2 border-l\"><a href=\"#\" class=\"inline-block py-2 px-3 text-grey-darkest hover:text-grey-dark no-underline\">Log In</a></li>\n";
echo "    <button class=\"bg-black hover:bg-grey-darker text-white ml-4 py-2 px-3\">\n";
echo "    Sign Up\n";
echo "    </button>\n";
echo "  </ul>\n";
echo "</nav><section class=\"font-sans h-screen w-full bg-cover text-center flex flex-col items-center justify-center\" style=\"background:url(https://stitches-cdn.hyperyolo.com/demo-bg.png) no-repeat center;\">\n";
echo "  <div class=\"bg-white text-black rounded-full h-16 w-16 flex items-center justify-center mb-8\"><i class=\"fas fa-play ml-1\"></i></div>\n";
echo "  <label for=\"tagline\" class=\"uppercase tracking-extrawide text-white text-xs font-hairline mt-8\">Watch Video</label>\n";
echo "  <h3 class=\"text-white mx-auto max-w-sm mt-4 font-normal text-2xl leading-normal\">Differentiate Yourself And Attract More Attention Sales And Profits</h3>\n";
echo "</section><section class=\"font-sans container max-w-xl m-auto flex flex-col lg:flex-row justify-center my-8\">\n";
echo "  <div class=\"order-2 lg:order-1 w-full lg:w-1/4 flex flex-col items-center lg:items-end justify-center text-center lg:text-right ml-0 lg:ml-8 mt-8\">\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Praesent placerat.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal mb-8\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Fusce pellentesque suscipit nibh.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal mb-8\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Ut aliquam sollicitudin leo.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    </div>\n";
echo "  <div class=\"order-1 lg:order-2 w-full lg:w-1/2 max-w-sm m-auto mb-6 lg:mb-0\">\n";
echo "    <img src=\"https://s3-us-west-2.amazonaws.com/968335633380.us-west-2.media/stitches/demo-phone.png\" alt=\"\">\n";
echo "  </div>\n";
echo "  <div class=\"order-last w-full lg:w-1/4 flex flex-col items-center lg:items-start justify-center text-center lg:text-left mt-8 mr-8\">\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Cras iaculis ultricies nulla.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal mb-8\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Praesent placerat risus quis eros.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal mb-8\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    <div class=\"w-12 h-12 rounded-full bg-grey-light mb-2\" alt=\"Avatar of Jonathan Reinink\"></div>\n";
echo "    <h2 class=\"text-black mb-2 font-normal\">Nunc dignissim risus id metus.</h2>\n";
echo "    <p class=\"text-grey-darker leading-normal\">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>\n";
echo "    </div>\n";
echo "</section><section class=\"font-sans container m-auto max-w-xl flex flex-col flex-wrap sm:flex-row justify-center\">\n";
echo "  <div class=\"w-full sm:w-1/2 lg:w-1/4 text-center py-8\">\n";
echo "    <label for=\"\" class=\"uppercase tracking-loose font-bold text-sm\">Basic Plan</label>\n";
echo "    <h1 for=\"\" class=\"uppercase tracking-loose font-bold text-5xl my-2\">$29<span class=\"text-grey-dark font-light text-xs\">/mo</span></h1>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">5</strong>Projects</p>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">20</strong>Images</p>\n";
echo "    <p class=\"mt-2 mb-6 text-grey-darker\"><strong class=\"text-black pr-2\">9/5</strong>Support</p>\n";
echo "    <button class=\"bg-transparent hover:bg-black text-black-dark font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent\">\n";
echo "    Buy Now\n";
echo "    </button>\n";
echo "  </div>\n";
echo "  <div class=\"w-full sm:w-1/2 lg:w-1/4 text-center py-8\">\n";
echo "    <label for=\"\" class=\"uppercase tracking-loose font-bold text-sm\">Team Plan</label>\n";
echo "    <h1 for=\"\" class=\"uppercase tracking-loose font-bold text-5xl my-2\">$59<span class=\"text-grey-dark font-light text-xs\">/mo</span></h1>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">10</strong>Projects</p>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">40</strong>Images</p>\n";
echo "    <p class=\"mt-2 mb-6 text-grey-darker\"><strong class=\"text-black pr-2\">12/7</strong>Support</p>\n";
echo "    <button class=\"bg-transparent hover:bg-black text-black-dark font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent\">\n";
echo "    Buy Now\n";
echo "    </button>\n";
echo "  </div>\n";
echo "  <div class=\"w-full sm:w-1/2 lg:w-1/4 text-center py-8\">\n";
echo "    <label for=\"\" class=\"uppercase tracking-loose font-bold text-sm\">Corporate Plan</label>\n";
echo "    <h1 for=\"\" class=\"uppercase tracking-loose font-bold text-5xl my-2\">$79<span class=\"text-grey-dark font-light text-xs\">/mo</span></h1>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">Unlimited</strong>Projects</p>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">Unlimited</strong>Images</p>\n";
echo "    <p class=\"mt-2 mb-6 text-grey-darker\"><strong class=\"text-black pr-2\">24/7</strong>Support</p>\n";
echo "    <button class=\"bg-transparent hover:bg-black text-black-dark font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent\">\n";
echo "    Buy Now\n";
echo "    </button>\n";
echo "  </div>\n";
echo "  <div class=\"w-full sm:w-1/2 lg:w-1/4 text-center py-8\">\n";
echo "    <label for=\"\" class=\"uppercase tracking-loose font-bold text-sm\">Enterprise Plan</label>\n";
echo "    <h1 for=\"\" class=\"uppercase tracking-loose font-bold text-5xl my-2\">$199<span class=\"text-grey-dark font-light text-xs\">/mo</span></h1>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">Unlimited</strong>Projects</p>\n";
echo "    <p class=\"my-2 text-grey-darker\"><strong class=\"text-black pr-2\">Unlimited</strong>Images</p>\n";
echo "    <p class=\"mt-2 mb-6 text-grey-darker\"><strong class=\"text-black pr-2\">24/7</strong>Support</p>\n";
echo "    <button class=\"bg-transparent hover:bg-black text-black-dark font-semibold hover:text-white py-2 px-4 border border-black hover:border-transparent\">\n";
echo "    Buy Now\n";
echo "    </button>\n";
echo "  </div>\n";
echo "</section><section class=\"bg-white py-4 font-sans\">\n";
echo "  <div class=\"container max-w-xl m-auto flex flex-wrap items-center justify-start\">\n";
echo "\n";
echo "    <div class=\"w-full md:w-1/2 lg:w-1/3 flex flex-col mb-8 px-3\">\n";
echo "      <div class=\"overflow-hidden bg-white rounded-lg shadow hover:shadow-raised hover:translateY-2px transition\">\n";
echo "        <img class=\"w-full\" src=\"https://stitches-cdn.hyperyolo.com/demo-bg.png\" alt=\"Sunset in the mountains\">\n";
echo "        <div class=\"p-6 flex flex-col justify-between \">\n";
echo "          <h3 class=\"font-medium text-grey-darkest mb-4 leading-normal\">Desktop Publishing Software like Aldus PageMaker</h3>\n";
echo "          <p class=\"inline-flex items-center\">\n";
echo "            <span class=\"text-grey-dark text-sm\">Read More</span>\n";
echo "          </p>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"w-full md:w-1/2 lg:w-1/3 flex flex-col mb-8 px-3\">\n";
echo "      <div class=\"overflow-hidden bg-white rounded-lg shadow hover:shadow-raised hover:translateY-2px transition\">\n";
echo "        <img class=\"w-full\" src=\"https://stitches-cdn.hyperyolo.com/demo-bg.png\" alt=\"Sunset in the mountains\">\n";
echo "        <div class=\"p-6 flex flex-col justify-between \">\n";
echo "          <h3 class=\"font-medium text-grey-darkest mb-4 leading-normal\">Desktop Publishing Software like Aldus PageMaker</h3>\n";
echo "          <p class=\"inline-flex items-center\">\n";
echo "            <span class=\"text-grey-dark text-sm\">Read More</span>\n";
echo "          </p>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"w-full md:w-1/2 lg:w-1/3 flex flex-col mb-8 px-3\">\n";
echo "      <div class=\"overflow-hidden bg-white rounded-lg shadow hover:shadow-raised hover:translateY-2px transition\">\n";
echo "        <img class=\"w-full\" src=\"https://stitches-cdn.hyperyolo.com/demo-bg.png\" alt=\"Sunset in the mountains\">\n";
echo "        <div class=\"p-6 flex flex-col justify-between \">\n";
echo "          <h3 class=\"font-medium text-grey-darkest mb-4 leading-normal\">Desktop Publishing Software like Aldus PageMaker</h3>\n";
echo "          <p class=\"inline-flex items-center\">\n";
echo "            <span class=\"text-grey-dark text-sm\">Read More</span>\n";
echo "          </p>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"w-full md:w-1/2 lg:w-1/3 flex flex-col mb-8 px-3\">\n";
echo "      <div class=\"overflow-hidden bg-white rounded-lg shadow hover:shadow-raised hover:translateY-2px transition\">\n";
echo "        <img class=\"w-full\" src=\"https://stitches-cdn.hyperyolo.com/demo-bg.png\" alt=\"Sunset in the mountains\">\n";
echo "        <div class=\"p-6 flex flex-col justify-between \">\n";
echo "          <h3 class=\"font-medium text-grey-darkest mb-4 leading-normal\">Desktop Publishing Software like Aldus PageMaker</h3>\n";
echo "          <p class=\"inline-flex items-center\">\n";
echo "            <span class=\"text-grey-dark text-sm\">Read More</span>\n";
echo "          </p>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"w-full md:w-1/2 lg:w-1/3 flex flex-col mb-8 px-3\">\n";
echo "      <div class=\"overflow-hidden bg-white rounded-lg shadow hover:shadow-raised hover:translateY-2px transition\">\n";
echo "        <img class=\"w-full\" src=\"https://stitches-cdn.hyperyolo.com/demo-bg.png\" alt=\"Sunset in the mountains\">\n";
echo "        <div class=\"p-6 flex flex-col justify-between \">\n";
echo "          <h3 class=\"font-medium text-grey-darkest mb-4 leading-normal\">Desktop Publishing Software like Aldus PageMaker</h3>\n";
echo "          <p class=\"inline-flex items-center\">\n";
echo "            <span class=\"text-grey-dark text-sm\">Read More</span>\n";
echo "          </p>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "\n";
echo "  </div>\n";
echo "</section><section class=\"font-sans container m-auto text-center py-8\">\n";
echo "  <label for=\"tagline\" class=\"uppercase tracking-wide font-bold text-grey-dark\">Various Aspects</label>\n";
echo "  <h1 class=\"mt-2 mb-4 font-medium max-w-sm m-auto\">Those are important in Vanue Management</h1>\n";
echo "  <hr class=\"border-b w-8 m-auto my-6\">\n";
echo "  <div class=\"flex flex-wrap justify-between items-start\">\n";
echo "    <div class=\"w-full sm:w-1/2 md:w-1/4 flex flex-col items-center justify-center p-4\">\n";
echo "      <div class=\"w-14 h-14 rounded-full mr-4 bg-grey-light\" alt=\"\"></div>\n";
echo "      <h2 class=\"my-4 font-medium\">Cras ornare tristique elit.</h2>\n";
echo "      <p class=\"leading-normal mb-4 text-grey-dark\">Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>\n";
echo "    </div>\n";
echo "    <div class=\"w-full sm:w-1/2 md:w-1/4 flex flex-col items-center justify-center p-4\">\n";
echo "      <div class=\"w-14 h-14 rounded-full mr-4 bg-grey-light\" alt=\"\"></div>\n";
echo "      <h2 class=\"my-4 font-medium\">Vivamus vestibulum ntulla nec ante.</h2>\n";
echo "      <p class=\"leading-normal mb-4 text-grey-dark\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n";
echo "    </div>\n";
echo "    <div class=\"w-full sm:w-1/2 md:w-1/4 flex flex-col items-center justify-center p-4\">\n";
echo "      <div class=\"w-14 h-14 rounded-full mr-4 bg-grey-light\" alt=\"\"></div>\n";
echo "      <h2 class=\"my-4 font-medium\">Praesent placerat risus quis eros.</h2>\n";
echo "      <p class=\"leading-normal mb-4 text-grey-dark\">Morbi in sem quis dui placerat ornare. Pellentesque odio nisi, euismod in, pharetra a, ultricies in, diam. Sed arcu. Cras consequat.</p>\n";
echo "    </div>\n";
echo "    <div class=\"w-full sm:w-1/2 md:w-1/4 flex flex-col items-center justify-center p-4\">\n";
echo "      <div class=\"w-14 h-14 rounded-full mr-4 bg-grey-light\" alt=\"\"></div>\n";
echo "      <h2 class=\"my-4 font-medium\">Fusce pellentesque suscipit nibh.</h2>\n";
echo "      <p class=\"leading-normal mb-4 text-grey-dark\">Praesent dapibus, neque id cursus faucibus, tortor neque egestas auguae, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.</p>\n";
echo "    </div>\n";
echo "  </div>\n";
echo "</section><section class=\"font-sans container m-auto flex flex-col py-8 max-w-xl text-center px-6\">\n";
echo "  <label class=\"text-sm uppercase\">20 Month 2019</label>\n";
echo "  <h1 class=\"my-8 max-w-full m-auto text-3xl md:text-4xl lg:text-5xl font-medium\">Lorem Ipsum is simply dummy text of the printing</h1>\n";
echo "  <p class=\"mt-1 lg:mt-4 max-w-lg m-auto leading-loose mb-6 text-left\">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.</p>\n";
echo "  <p class=\"max-w-lg m-auto leading-loose mb-6 text-left\">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>\n";
echo "</section>\n";
echo "<section class=\"antialiased font-sans w-full bg-grey-lighter text-left text-black py-8\">\n";
echo "  <div class=\"container mx-auto max-w-xl py-8 font-normal leading-normal\">\n";
echo "    <h3 class=\"text-2xl\">Grow Your Business</h3>\n";
echo "    <p class=\"\">Build high performing teams, establish design practices, mentor and grow the next generation of great designers, and design interfaces and experiences.</p>\n";
echo "    <div class=\"max-w-sm mt-4 sm:flex\">\n";
echo "      <input type=\"email\" class=\"block w-full focus:outline-0 bg-white py-3 px-6 mb-2 sm:mb-0\" name=\"email\" placeholder=\"Enter your email\" required=\"\">\n";
echo "      <button class=\"uppercase text-sm text-white focus:outline-0 w-full sm:w-auto bg-black hover:bg-grey-darkest focus:bg-grey-light tracking-wide px-6\">Subscribe</button>\n";
echo "    </div>\n";
echo "  </div>\n";
echo "</section><section class=\"font-sans container m-auto flex flex-col md:flex-row py-8 max-w-xl px-6 lg:px-0\">\n";
echo "  <div class=\"w-full md:w-1/4 border-b md:border-0 mb-6 md:mb-0 pb-6 md:pb-0 pr-8 flex justify-center items-start flex-col\">\n";
echo "    <label for=\"\" class=\"font-bold\">Important Note</label>\n";
echo "    <p class=\"leading-normal mt-4 border-0 md:border-r md:pr-2\">Nullam gravida sem vel massa pulvinar cursus. In sagittis enim vitae eros ultrices sagittis</p>\n";
echo "  </div>\n";
echo "  <div class=\"w-full md:w-3/4 leading-normal column-0 lg:column-2\">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\n";
echo "  The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. </div>\n";
echo "</section>\n";
echo "<footer class=\"font-sans bg-black text-white py-8 px-4\">\n";
echo "  <div class=\"mx-auto container overflow-hidden flex flex-col lg:flex-row justify-between\">\n";
echo "    <a href=\"/\" class=\"block mr-4 w-1/2\">\n";
echo "      <img src=\"https://stitches-cdn.hyperyolo.com/logo-white.png\" class=\"w-32\" alt=\"logo\">\n";
echo "    </a>\n";
echo "    <div class=\"w-1/2 flex text-sm mt-6 lg:mt-0\">\n";
echo "      <ul class=\"text-grey-dark list-reset font-thin flex flex-col text-left\">\n";
echo "        <li class=\"inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide\">Product</li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Popular</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Trending</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Catalog</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Features</a></li>\n";
echo "      </ul>\n";
echo "      <ul class=\"text-grey-dark list-reset font-thin flex flex-col text-left\">\n";
echo "        <li class=\"inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide\">Company</li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Press Release</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Mission</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Strategy</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Works</a></li>\n";
echo "      </ul>\n";
echo "      <ul class=\"text-grey-dark list-reset font-thin flex flex-col text-left\">\n";
echo "        <li class=\"inline-block py-2 px-3 text-white uppercase no-underline font-medium tracking-wide\">Info</li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Support</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Developers</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Customer Services</a></li>\n";
echo "        <li><a href=\"#\" class=\"inline-block py-2 px-3 text-grey hover:text-grey-light no-underline\">Started Guide</a></li>\n";
echo "      </ul>\n";
echo "      <div class=\"text-grey-dark flex flex-col\">\n";
echo "        <div class=\"inline-block py-2 px-3 text-white uppercase font-medium tracking-wide\">Follow Us</div>\n";
echo "        <div class=\"flex pl-4 justify-start\">\n";
echo "          <a class=\"block flex items-center text-white hover:text-grey mr-6 no-underline\" href=\"#\"><i class=\"fab fa-github-alt\"></i></a>\n";
echo "          <a class=\"block flex items-center text-white hover:text-grey mr-6 no-underline\" href=\"#\"><i class=\"fab fa-slack\"></i></a>\n";
echo "          <a class=\"block flex items-center text-white hover:text-grey no-underline\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </div>\n";
echo "  <div class=\"pt-4 mt-4 text-grey-darker border-t border-grey-darkest text-center\"> ©2019 Hyperyolo. All rights reserved.</div>\n";
echo "</footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
echo "";
?>